services:
  selenium-hub7:
    image: selenium/hub:latest
    container_name: selenium-hub7
    ports:
      - "4471:4471"
      - "4472:4472"
      - "4473:4473"
      - "4477:4477"

  chrome7:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub7
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub7
      - SE_EVENT_BUS_PUBLISH_PORT=4472
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4473
 
